linters:
  enable:
    - dupl
    - errcheck
    - funlen
    - goconst
    - godot
    - gofmt
    - mnd
    - gosimple
    - govet
    - ineffassign
    - predeclared
    - unused
    - thelper
    - typecheck
    - revive
    - unparam
    - unused
    - wastedassign
    - whitespace

linters-settings:
  revive:
    ignore-generated-header: false
    severity: error
    confidence: 0.8
    rules:
      - name: exported
  funlen:
    lines: 70
    statements: 50
  gofmt:
    simplify: true
  gomnd:
    checks: argument,case,condition,operation,return,assign
  ifshort:
    max-decl-lines: 1
    max-decl-chars: 30
  unparam:
    check-exported: false

issues:
  exclude:
    - EXC0012
  exclude-use-default: false