version: '3.8'

services:
  userservice:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment: 
      - MONGO_URL=mongodb://mongodb:27017
      - MONGO_DATABASE=cnm_proyect
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks: 
      - mynetwork
    
networks:
  mynetwork:
    driver: bridge

